#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# AWS autocomplete
#
if [[ -a "/usr/local/aws/bin/aws_zsh_completer.sh" ]]; then
  source "/usr/local/aws/bin/aws_zsh_completer.sh" 
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
